#################################################################
# HBase
# https://hbase.apache.org
name: Release HBase Images

on:
  push:
    branches:
      - master

jobs:
  #################################################################
  # HBase
  release:
    name: Release HBase Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker(QEMU)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker(Buildx)
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push images
        uses: docker/bake-action@v4
        with:
          targets: hbase
          workdir: ./hbase
          push: true