############################################################################
# Install Pinpoint Java Agent
# https://central-x.com
############################################################################
name: Release Install Pinpoint Java Agent Images

on:
  workflow_dispatch:

jobs:
  #################################################################
  # Install Pinpoint Java Agent
  release:
    name: Release Install Pinpoint Java Agent Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker(QEMU)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker(Buildx)
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push install-pinpoint-java-agent images
        uses: docker/bake-action@v4
        with:
          targets: install-pinpoint-java-agent
          workdir: ./install-pinpoint-java-agent
          push: true