############################################################################
# Maven with Azul Zulu OpenJDK
# https://maven.apache.org
# https://www.azul.com
############################################################################
name: Release Maven Images

on:
  workflow_dispatch:

jobs:
  #################################################################
  # Release Maven
  release:
    name: Release Maven Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker(QEMU)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker(Buildx)
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #============================ Build ============================
      - name: Release Images
        uses: docker/bake-action@v5
        with:
          targets: maven
          workdir: ./maven
          push: true
  #################################################################
  # Test Maven
  test:
    name: Test Maven Images
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      matrix:
        version: [3]
        openjdk: [8, 11, 17, 21]
        os: ["ubuntu", "alpine"]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #======================== Test OpenJDK =========================
      - name: Test Images
        run: docker run --rm centralx/maven:${{ matrix.version }}-jdk${{ matrix.openjdk }}-${{ matrix.os }}