#################################################################
# Resources Installer
# https://central-x.com
name: Release Resources Installer Images

on:
  push:
    branches:
      - master

jobs:
  #################################################################
  # Resources Installer
  openjdk8:
    name: Release Resources Installer Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker(QEMU)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker(Buildx)
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push resources-installer images
        uses: docker/bake-action@v4
        with:
          targets: resources-installer
          workdir: ./resources-installer
          push: true