############################################################################
# Spring Boot Application Runner
# https://spring.io
############################################################################
name: Release Spring Runner Images

on:
  workflow_dispatch:

jobs:
  #################################################################
  # Release Spring Runner
  release:
    name: Release Spring Runner Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker(QEMU)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker(Buildx)
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #============================ Build ============================
      - name: Release Images
        uses: docker/bake-action@v4
        with:
          targets: spring-runner
          workdir: ./spring-runner
          push: true
  #################################################################
  # Test Spring Runner
  test:
    name: Test Spring Runner Images
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      matrix:
        version: [8, 11, 17, 21]
        java: ["jdk", "jre"]
        os: ["ubuntu", "alpine"]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #======================== Test OpenJDK =========================
      - name: Test Images
        run: docker run --rm centralx/spring-runner:${{ matrix.java }}${{ matrix.version }}-${{ matrix.os }} java -version